# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: no-commit-to-branch

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.11.0 # automatically updated by Commitizen
    hooks:
      - id: commitizen

  - repo: local
    hooks:
      - id: yarn install
        name: yarn install
        entry: yarn install
        language: system
        pass_filenames: false

      - id: Linters
        name: yarn lint
        entry: yarn lint:fix
        language: system
        pass_filenames: false
